spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

# Gateway-specific resilience (if you run the CB at the Gateway level)
resilience4j:
  circuitbreaker:
    instances:
      gatewayCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
